// Date: 7/5/2016 5:45:18 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package azaka7.algaecraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOyster extends ModelBase
{
  //fields
    ModelRenderer bottom;
    ModelRenderer top;
    ModelRenderer pearl;
  
  public ModelOyster()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      bottom.mirror = true;
      bottom = new ModelRenderer(this, 0, 9);
      bottom.addBox(0F, 0F, 0F, 6, 1, 8);
      bottom.setRotationPoint(-3F, 23F, -4F);
      bottom.setTextureSize(64, 32);
      bottom.mirror = true;
      setRotation(bottom, 0F, 0F, 0F);
      bottom.mirror = false;
      top = new ModelRenderer(this, 0, 0);
      top.addBox(0F, 0F, -0.5F, 6, 1, 8);
      top.setRotationPoint(-3F, 22.3F, -4F);
      top.setTextureSize(64, 32);
      top.mirror = true;
      setRotation(top, 0.2898899F, 0F, 0F);
      pearl = new ModelRenderer(this, 60, 0);
      pearl.addBox(2.5F, 0F, 3.5F, 1, 1, 1);
      pearl.setRotationPoint(-3F, 22.2F, -4F);
      pearl.setTextureSize(64, 32);
      pearl.mirror = true;
      setRotation(pearl, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    bottom.render(f5);
    top.render(f5);
    pearl.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
