// Date: 2/28/2016 4:09:00 PM
// Template version 1.1
// Java generated by Techne
package azaka7.algaecraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBrazier0 extends ModelBase
{
  //fields
    ModelRenderer base1;
    ModelRenderer base2;
    ModelRenderer basePole;
    ModelRenderer topPole;
    ModelRenderer topPlate;
    ModelRenderer topSpike1;
    ModelRenderer topSpike2;
    ModelRenderer topSpike3;
    ModelRenderer topSpike4;
    ModelRenderer topSpike5;
    ModelRenderer topSpike6;
    ModelRenderer topSpike7;
    ModelRenderer topSpike8;
    ModelRenderer topFlame;
  
  public ModelBrazier0()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      base1 = new ModelRenderer(this, 0, 0);
      base1.addBox(0F, 0F, 0F, 6, 2, 6);
      base1.setRotationPoint(-3F, 22F, -3F);
      base1.setTextureSize(64, 64);
      base1.mirror = true;
      setRotation(base1, 0F, 0F, 0F);
      base2 = new ModelRenderer(this, 0, 8);
      base2.addBox(0F, 0F, 0F, 4, 1, 4);
      base2.setRotationPoint(-2F, 21F, -2F);
      base2.setTextureSize(64, 64);
      base2.mirror = true;
      setRotation(base2, 0F, 0F, 0F);
      basePole = new ModelRenderer(this, 56, 0);
      basePole.addBox(0F, 0F, 0F, 2, 13, 2);
      basePole.setRotationPoint(-1F, 8F, -1F);
      basePole.setTextureSize(64, 64);
      basePole.mirror = true;
      setRotation(basePole, 0F, 0F, 0F);
      topPole = new ModelRenderer(this, 56, 13);
      topPole.addBox(0F, 0F, 0F, 2, 10, 2);
      topPole.setRotationPoint(-1F, -2F, -1F);
      topPole.setTextureSize(64, 64);
      topPole.mirror = true;
      topPole.offsetY = 1;
      setRotation(topPole, 0F, 0F, 0F);
      topPlate = new ModelRenderer(this, 0, 13);
      topPlate.addBox(0F, 0F, 0F, 4, 1, 4);
      topPlate.setRotationPoint(-2F, -3F, -2F);
      topPlate.setTextureSize(64, 64);
      topPlate.mirror = true;
      topPlate.offsetY = 1;
      setRotation(topPlate, 0F, 0F, 0F);
      topSpike1 = new ModelRenderer(this, 48, 0);
      topSpike1.addBox(0F, 0F, 0F, 1, 6, 1);
      topSpike1.setRotationPoint(2F, -6F, -0.5F);
      topSpike1.setTextureSize(64, 64);
      topSpike1.mirror = true;
      topSpike1.offsetY = 1;
      setRotation(topSpike1, 0F, 0F, 0F);
      topSpike2 = new ModelRenderer(this, 52, 0);
      topSpike2.addBox(0F, 0F, 0F, 1, 8, 1);
      topSpike2.setRotationPoint(1.5F, -8.5F, 1.5F);
      topSpike2.setTextureSize(64, 64);
      topSpike2.mirror = true;
      topSpike2.offsetY = 1;
      setRotation(topSpike2, 0F, 0F, 0F);
      topSpike3 = new ModelRenderer(this, 48, 0);
      topSpike3.addBox(0F, 0F, 0F, 1, 6, 1);
      topSpike3.setRotationPoint(-0.5F, -6F, 2F);
      topSpike3.setTextureSize(64, 64);
      topSpike3.mirror = true;
      topSpike3.offsetY = 1;
      setRotation(topSpike3, 0F, 0F, 0F);
      topSpike4 = new ModelRenderer(this, 52, 0);
      topSpike4.addBox(0F, 0F, 0F, 1, 8, 1);
      topSpike4.setRotationPoint(-2.5F, -8.5F, 1.5F);
      topSpike4.setTextureSize(64, 64);
      topSpike4.mirror = true;
      topSpike4.offsetY = 1;
      setRotation(topSpike4, 0F, 0F, 0F);
      topSpike5 = new ModelRenderer(this, 48, 0);
      topSpike5.addBox(0F, 0F, 0F, 1, 6, 1);
      topSpike5.setRotationPoint(-3F, -6F, -0.5F);
      topSpike5.setTextureSize(64, 64);
      topSpike5.mirror = true;
      topSpike5.offsetY = 1;
      setRotation(topSpike5, 0F, 0F, 0F);
      topSpike6 = new ModelRenderer(this, 52, 0);
      topSpike6.addBox(0F, 0F, 0F, 1, 8, 1);
      topSpike6.setRotationPoint(-2.5F, -8.5F, -2.5F);
      topSpike6.setTextureSize(64, 64);
      topSpike6.mirror = true;
      topSpike6.offsetY = 1;
      setRotation(topSpike6, 0F, 0F, 0F);
      topSpike7 = new ModelRenderer(this, 48, 0);
      topSpike7.addBox(0F, 0F, 0F, 1, 6, 1);
      topSpike7.setRotationPoint(-0.5F, -6F, -3F);
      topSpike7.setTextureSize(64, 64);
      topSpike7.mirror = true;
      topSpike7.offsetY = 1;
      setRotation(topSpike7, 0F, 0F, 0F);
      topSpike8 = new ModelRenderer(this, 52, 0);
      topSpike8.addBox(0F, 0F, 0F, 1, 8, 1);
      topSpike8.setRotationPoint(1.5F, -8.5F, -2.5F);
      topSpike8.setTextureSize(64, 64);
      topSpike8.mirror = true;
      topSpike8.offsetY = 1;
      setRotation(topSpike8, 0F, 0F, 0F);
      topFlame = new ModelRenderer(this, 0, 60);
      topFlame.addBox(0F, 0F, 0F, 2, 2, 2);
      topFlame.setRotationPoint(-1F, -5.5F, -1F);
      topFlame.setTextureSize(64, 64);
      topFlame.mirror = true;
      topFlame.offsetY = 1;
      setRotation(topFlame, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
	if(f == 0){
		base1.render(f5);
    	base2.render(f5);
    	basePole.render(f5);
	} else {
		topPole.render(f5);
		topPlate.render(f5);
		topSpike1.render(f5);
		topSpike2.render(f5);
		topSpike3.render(f5);
    	topSpike4.render(f5);
    	topSpike5.render(f5);
    	topSpike6.render(f5);
    	topSpike7.render(f5);
    	topSpike8.render(f5);
    	topFlame.render(f5);
	}
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
